### ISSUE TITLE
Extend data format to support timing information

### ISSUE THREAD

**Issue by hellais** [ooni/spec#91] opened 2017-10-10 16:41 UTC
This is related to: https://github.com/measurement-kit/measurement-kit/issues/1414

**Comment by bassosimone** [comment] 2019-06-18 18:40
I believe using HAR #93 is a good idea. Still, the problem becomes how to continue generating the existing data format and using HAR. There would be duplication.

My tentative plan is the following:

1. submit both the existing format and HAR for some time and use cross referencing to make sure that the two formats are clearly interlinked; and/or

2. teach the new collector to parse HAR and (also?) emit the existing data format

3. spend more time thinking

**Comment by hellais** [comment] 2019-06-19 09:55
Another option could be that of creating some logic (in the pipeline) that converts the http test template from the current format into HAR.

I don't think we want to be duplicating the data in the measurements especially the HTTP data which makes up for the majority of our data storage usage. Rather if we decide to not implement a compatibility layer we can just add more logic in the pipeline to support parsing both of these formats.

**Comment by bassosimone** [comment] 2019-06-19 10:42
@hellais, thanks for adding to this issue! It didn't cross my mind this possibility! I have some issues however with the following sentence, as explained below:

> some logic (in the pipeline) that converts the http test template from the current format into HAR

To do this, we actually need to extend our data format to include timing information. I believe the design effort is lower if we're using HAR directly. (I have now worked with HAR for some hours and it seems we can represent the data emitted by Web Connectivity with HAR plus OONI defined extensions to the HAR format; e.g., for the result of the DNS, the connects performed.)

If you remember, yesterday I spent quite some time asking questions about the data format. It was meant to understand the complexity of using HAR more widely, even though my initial question was more limited an pertaining mainly to changing headers to be a list rather than a map.

Another aspect to keep in mind, and that perhaps can further strengthen your proposal of performing such changes in the pipeline, is that actually we can _submit_ an HAR based data format and then generate in the pipeline the existing format for existing data consumer. Another option, again assuming we want to keep existing data consumer happy and proceed piecemeal, is to have the API generate on the fly the existing data format if requested.

The design space is not infinite, but there are a bunch of choices here. I have a sense that I do have a preference for going towards emitting more standard (e.g. HAR) pieces of data in the probe and then this begs the question of whether to glue the HAR with the existing data format. My preference is driven by the fact that we can use that data at different levels to know more about the performance of our tools with standard analysis mechanisms already available for HAR. Consider, e.g., the case where we can dump the HAR of all our interactions with the OONI backends and then submit some of them sometimes. This could help us understanding how our users are connecting to us, and can help us evaluate how to make tests faster, by _also_ taking into account contacting OONI services.

My initial iteration of solving this problem of enabling more standard analysis is that of using HAR _internally_ to ooni/probe-engine to perform HTTP based measurements. Then I'll implement Web Connectivity, but also all the other experiments that use HTTP, as wrappers around that functionality that applies the required data transformations to HAR. (I am considering to use Jsonnet for this however I cannot decide whether this statement is serious or not :-P.) Proceeding like this is sane because it gives us time, when we can, to move the boundary between HAR and our current data format in an incremental way. Do you agree that this incremental HAR rollout is sane?

**Comment by hellais** [comment] 2019-06-19 11:46
> To do this, we actually need to extend our data format to include timing information.

Not necessarily. If it's desirable do have the data in the same format for parsing reasons we can either omit certain fields (the conversion from JSON -> HAR will only implement a subset of the features supported by HAR) or we can populate them with dummy values which have some meaning but we know to not consider them as useful as other values.

**Comment by bassosimone** [comment] 2019-06-19 14:37
@hellais right, but if we don't want to discard the data, we need the HAR (or any other format with equivalent semantic) to hit at least the collector. Then I agree with you that once we have collected the _more-data-than-before_ we can perform lossy transformations for legacy reasons. Or is there a way of doing this that I am missing and we can get away with?

**Comment by hellais** [comment] 2019-11-20 10:49
I believe @bassosimone has been working on stuff related to this inside of netx.

**Comment by bassosimone** [comment] 2020-01-12 13:38
I have implemented this in probe-engine and to this repository as part of https://github.com/ooni/probe-engine/issues/226. The relevant diff is: https://github.com/ooni/spec/compare/1028eee924e855db0a6688ee6f3df615b45d0be5...4bfd1de52ab102566dbf2f7f0efce1b70be00478

**Comment by bassosimone** [comment] 2020-01-12 13:39
Also, with the unified place for issues, this is actually a duplicate of: https://github.com/ooni/probe-engine/issues/12

**Closed by bassosimone** 2020-01-12 13:39 UTC
Labels: enhancement, priority/medium
